#网站配置
host: http://108.170.5.74:8080/
name: 【这里修改为你自己的用户名】
password: 【这里修改为你自己的密码】
#评论字典
comment:
  - 守望着天空，大海，和你的回忆。
  - 潮水中沉没着被遗忘的名字，它们溺死于自作多情的泡沫。
  - 在我手里，正义从不会迟到半秒。
  - 空洞和孤独，依靠温暖的灯光填补。
  - 有种愚弄自己的东西，叫忠诚。
  - 破碎的奇迹好过没有，苦恼的希望胜于迷茫。
  - 你整个人都是注水的。
  - 守护爱人的心，因恐惧失去而污秽。
  - 点亮的星，不会轻易熄灭。
  - 守望着天空  - 大海和你的回忆。
  - 完美，是最无情的禁锢。
  - 逆流而上吧！
  - 会原谅，我的任性吗？
  - 对你们很失望。
  - 在对决时刻，我的心是一块石头。
  - 前往需要你们的地方。
  - 没有方向的河流，终会枯竭。
  - 哎呀，我可是吓的瑟瑟发抖呢，阁下。
  - 你的魔道不够纯粹。
  - 翻船哈哈哈。
  - 点亮的心，不会轻易熄灭。
  - 请原谅我的任性。
  - 守望着天空，大海和你的电梯。
  - 好好，干得不错。
  - 魔道的天才们，属于同一种流派：偶像派。
  - 海边吹来的风，永远那么安宁。
  - 你们可真让人伤心。
  - 螳螂捕蝉，黄雀在后。
  - 演奏你的胡笳琴，或者，被胡笳琴所演奏。
  - 点亮的心不轻易熄灭。
  - 映照潮汐的起伏，以免迷失战场的倒影。
  - 前往需要你的地方。
  - 今天和大家过的一样普普通通。
  - 此时相望不相闻，愿逐月华流照君。鸿雁长飞光不度，鱼龙潜跃水成文。
  - 你看不见的眼里，隐藏着污秽。
  - 羡慕，因为是我想的模样。
  - 魔道的天才们属于同一种流派，偶像派。
  - 映照潮汐的起伏，以免迷失战场的道路。
  - 看不见的那只眼里，有你不该看见的过去。
